blank_issues_enabled: false
contact_links:
  - name: Vorschläge zu anderen Themen
    url: https://www.pietsmiet.de/community/suggestions
    about: Wenn du Vorschläge zu Themen hast, die nicht die Website betrifft, klickt bitte hier.
